name: LobbyItems
author: Vecnavium
description: A PocketMine-MP Plugin that allows you to have lobby items and execute a specific command
main: Vecnavium\LobbyItems\Main
version: 2.0.1
api: 4.0.0
